### ISSUE TITLE
Many advertised servers attacked by DDoS at UTC 8:25, Feb 8

### ISSUE THREAD

**Issue by tangbiao828** [TLeonardUK/ds3os#101]
Something bad is happening as the DS3OS increasing attentioned. 
This muti DDoS attacks maybe for some exact purpose, or not, anyway I have no idea.
No-advertised servers avoid this DDoS attack, still runs well.
Wondering a way to protect the advertised server running in entry-level ECS instead of by importing server config to entry server...
It seems old release version of Loader hides server IP but 0.13 and 0.14 verson as I know shows publicly. 
Could it possible to return the changes for hiding IP address in all releases so far?
Also, in my unprofessional idea, is it better to sort advertised servers by more options? (languages maybe? a clean Loader for other area user... just my guess)
Anyway, thanks for the contributions of Dark Souls community.

**Comment by TLeonardUK** [comment]
> It seems old release version of Loader hides server IP but 0.13 and 0.14 verson as I know shows publicly.
Nothing is hidden or shielded, the IP's are by nature of being needed for a connection, public knowledge.

All that change does is show them in the UI to make debugging issues easier, I'm not going to remove them.

**Comment by tangbiao828** [comment]
> If you want to protect against DDoS attacks you need to use typical mitigation methods, which are not typically software-level.
 Sorry for my poor knowledge about it. Seems the most possible way to avoid DDoS is using no-advised server. :D
