### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by mengwei1** [TLeonardUK/ds3os#102]
I am running server on a cloud server, OS is Windows-2019-Datacenter-cn.
Logging into webui works well
![webui](https://user-images.githubusercontent.com/12697353/153034640-ee649edf-b13d-4193-82ee-53dd5e1c3bbc.png)

Netcat shows all server ports' connectivity is good
![nc](https://user-images.githubusercontent.com/12697353/153035463-70aa2dda-739a-4d87-b8e3-fcc8d715a7ec.png)

While I run loader as admin,I can connect to other servers
![official](https://user-images.githubusercontent.com/12697353/153035987-ff9f0ba1-e205-45fa-8b0a-1290d43c40dc.png)
![shanghaidianxin](https://user-images.githubusercontent.com/12697353/153036001-3e37118f-7d1f-4258-8875-241c050b6d48.png)

but i can't connect to my server
![fail](https://user-images.githubusercontent.com/12697353/153036541-d571b932-1ba2-4a22-80c4-7547ecbb1f3f.png)

Below is my ds3osconfig

{
    "Description": "",
    "Hostname": "222.187.222.121",
    "ModsBlacklist": "",
    "ModsRequiredList": "",
    "ModsWhitelist": "",
    "Name": "测试",
    "PrivateHostname": "222.187.222.121",
    "PublicKey": "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEA1Qa33IsNGnnzw7DMsuN7AFpDwqqMZEHpEwvWAMnfqOZWvFvOsAdG\nSSJB6YBajygDx/JSQOzFQap/EzrxbZfZ2g+bwcVLypEa6NZU0pdehFNPe2W0z7/e\n5XGZ/cc7oP9peRDvMX7+kxaGuaRIGKFkbc7RqmQn3xlk/ITNIJ57WGGQX97RvsbQ\nzgbJ5/L6BJBBjTSqaRcHolxQ3hOWztUvOV2oNytzc8SFRbEbo+8guUmDp+rUD50b\nnPG3xP10JD79GCLDH0t8j7dE0nV811xHDxme7JKbglVsHCZKvxtUnhq2N+6YZLDi\nkAieVUVURtJREO0IQo+pEXMCi5iROqngkwIDAQAB\n-----END RSA PUBLIC KEY-----\n"
}

**Comment by mengwei1** [comment]
When I run ipconfig:
![ipconfig](https://user-images.githubusercontent.com/12697353/153037080-b4758a95-cedb-4e7d-9164-6bbbc9df186f.png)

**Comment by TurkeyGuoba** [comment]
云服务器端口没开放？

**Comment by mengwei1** [comment]
Port 50050(Login server port) is banned due to some policy on my cloud server, I have to change that to another port in config.json. But when I monitor the port which DrakSouls3 is actually connecting to, I found it is still 50050. It seems that changing server port in config.json doesn't work for client's loader.

**Comment by TLeonardUK** [comment]
Yeh you can't change that port, it shouldnt actually be in the config file. Its hardcoded into the game and we don't currently support patching it.
