### ISSUE TITLE
Logging in doesn't work on WebUI

### ISSUE THREAD

**Issue by brandon-dodds** [TLeonardUK/ds3os#108]
I've tried to log into the web-ui by setting a username and password in the fields (and also the default of leaving them blank). I cannot access it. Screenshots below (using Windows 11)
![image](https://user-images.githubusercontent.com/60390818/153731232-24835ada-c55b-4217-a492-98aff8310771.png)

**Comment by brandon-dodds** [comment]
![image](https://user-images.githubusercontent.com/60390818/153744898-175533a9-c2cb-4182-8596-c2dfc23d28fa.png)
![image](https://user-images.githubusercontent.com/60390818/153744925-ae27c2fb-01fe-4813-a15c-c53dd998b8ba.png)
![image](https://user-images.githubusercontent.com/60390818/153744952-a5e2dd27-0534-49b6-979f-95ebeebc8097.png)
I get a 401 unauthorized. I've tried it on a fresh reinstall too and I cannot login on that either

**Comment by TLeonardUK** [comment]
Read your config file, you have username and password switched around.

**Comment by brandon-dodds** [comment]
So you're right, a good reminder to not make issues when I'm half asleep. I just tried it and it worked. Thanks a lot and thank you for your excellent contribution to the Dark Souls community.
