### ISSUE TITLE
cant summon or get summoned

### ISSUE THREAD

**Issue by Grabisoft** [TLeonardUK/ds3os#11]
Hi so im testing this on multiple PCs in my LAN and also using external connections. so far ive been able to "connect" between PCs, i see phantoms running around and i can place soapstones to summon and i can see soapstones planted.
The problem is when i try to connect to the other player when actually call for summoning. the summoning always fails. i will show the steps of everything and a screen of the server errors i get.
![start](https://user-images.githubusercontent.com/16512014/133702694-c0b5531f-3f30-4eae-9458-cd28647e7eb2.jpg)
![being summoned](https://user-images.githubusercontent.com/16512014/133702728-48b28546-91cf-432b-aefc-6c8a03514bae.jpg)
![unable](https://user-images.githubusercontent.com/16512014/133702730-5cda90fe-5f30-4a2d-b455-9afa2ee9bbca.jpg)

![asd](https://user-images.githubusercontent.com/16512014/133702738-2beeb174-17d2-459f-8289-c5116491862a.png)

help would be appreciated thank you

**Comment by TLeonardUK** [comment]
Is this going through steam?

**Comment by Grabisoft** [comment]
> Is this going through steam?

im.  testing using goldberg

**Comment by TLeonardUK** [comment]
As I said in the previous thread, I don't support non-steam clients. If you can reproduce this problem on steam I'll take a look at it.

For what its worth Jeyyu has this working in goldberg so you can talk to him if you wish - https://github.com/TLeonardUK/ds3os/issues/1
