### ISSUE TITLE
Crashing with Dancer and Aldrich.

### ISSUE THREAD

**Issue by Pfctink** [TLeonardUK/ds3os#116]
I have a friend who is crashing when trying to enter the Dancers and Aldrich. We worked around Aldrich by putting my sign next to the fog wall, but it crashes on the Dancer when the cutscene ends.

For reference, I think it's because they're on Windows 11 and this mod likely doesn't play well with Windows 11. I don't know if there's anything that can be done, as we've tried everything other than reinstalling the game fresh (because it gets rid of the character if we do that, happened to me several times, happened to them once)

**Comment by TLeonardUK** [comment]
I'm guessing you are using blue sentinel, this is a known bug in it, and there are other closed issues regarding it. This cannot be solved by ds3os, it needs the BS authors to release an update.

**Comment by Pfctink** [comment]
Alright, thank you.
