### ISSUE TITLE
[QUESTION] Workaround for Linux?

### ISSUE THREAD

**Issue by NullDev** [TLeonardUK/ds3os#118]
I play all games with Proton and this it not an "issue" by any means but rather just a question. 
Does anyone know how I'd go about using this on Linux?
Like, just running it in the Proton prefix doesn't work unfortunately

**Comment by Grammernatzi** [comment]
https://github.com/TLeonardUK/ds3os/issues/30#issuecomment-1038068886

**Comment by NullDev** [comment]
Oh welp... Sorry about that. Didn't expect anyone to actually try that as well :') 
Thank you!
