### ISSUE TITLE
[BUG] Server Config will be resetted, if you start the server

### ISSUE THREAD

**Issue by Zeromix9** [TLeonardUK/ds3os#120]
Hello there,
if I´m changing the Server Configuration file. (server.ds3osconfig) like for example the name, it will get resetted, as soon as I start the server.

**Comment by TLeonardUK** [comment]
That's not a bug, that's by design. You should be modifying the server config not that file, that file will always be kept up to date with the contents of the server config when it's run.

**Comment by Zeromix9** [comment]
Which file exacly? Cause your readme says:
"When launched it will save 
a file to Saved\server.ds3oconfig, this file contains configuration settings 
and cryptographic keys that allow other users to join the server. You should 
open this file and modify the Name, Description and Hostname settings your
server."

So that´s a bit confusing.

**Comment by TLeonardUK** [comment]
Saved\config.json is the server configuration file.

And yeh, some of the documentation is from earlier in development, it needs updating when I have the chance.
