### ISSUE TITLE
DIsable to find any servers.

### ISSUE THREAD

**Issue by roundlessx** [TLeonardUK/ds3os#124]
I can get into the offical unofficial server yesterday ,but now no server can be found. I ask the furum it seems that it is not a particular bug.
![屏幕截图 2022-03-10 173934](https://user-images.githubusercontent.com/45331619/157634507-557dd1f5-def3-437b-91b1-d62a984b3a96.png)

**Comment by TLeonardUK** [comment]
This was likely due to a reboot of the master server that happened around then.
