### ISSUE TITLE
Loader.exe no longer retains server information

### ISSUE THREAD

**Issue by Adephx** [TLeonardUK/ds3os#13]
As title. Loader.exe will no longer retain the server information from the `server.ds3osconfig` file after you either launch the game or close the Loader.exe.

**Comment by TLeonardUK** [comment]
Ah yeh, my mistake, made some changes to how it refreshes the server list, looks like I forgot to exclude manually imported configurations. I'll put a fix in later.

**Comment by TLeonardUK** [comment]
Should be fixed in latest, reopen if it isn't.
