### ISSUE TITLE
Failed to launch data souls 3 executable

### ISSUE THREAD

**Issue by Vitaonx** [TLeonardUK/ds3os#131]
![image](https://user-images.githubusercontent.com/96921060/160211219-cf0783de-41ce-4abc-8c77-e6445888146f.png)

**Comment by Grammernatzi** [comment]
Is your copy of Dark Souls 3 legit? That's not a steam folder it's pointing to.

**Comment by Vitaonx** [comment]
> Is your copy of Dark Souls 3 legit? That's not a steam folder it's pointing to.

Unfortunately my game is cracked, the folder is the one I selected to install

**Comment by TLeonardUK** [comment]
We do not support pirated copies of the game.

**Comment by Vitaonx** [comment]
> We do not support pirated copies of the game.

Então foda-se.
