### ISSUE TITLE
Some suggestions for loader

### ISSUE THREAD

**Issue by dysf888** [TLeonardUK/ds3os#139]
I strongly recommended to remove the server IP display and add sending packets to random IP addresses
![image](https://user-images.githubusercontent.com/47450409/161426597-fd9d9fab-311a-4fbf-a036-e520242aa8ca.png)
After removing and adding random sending packets, we have hardly suffered DDoS attacks
![1](https://user-images.githubusercontent.com/47450409/161426830-09a09ee3-8a53-47e1-899f-b5017cb43e52.png)

**Comment by TLeonardUK** [comment]
> I strongly recommended to remove the server IP display
The server IP is public knowledge, removing the display does nothing but make diagnosing peoples issues more difficult. Its trivial to retrieve that information with or without the display.

> add sending packets to random IP addresses
I'm not sure what you mean by this.

**Comment by dysf888** [comment]
Some ways to prevent capturing packets to obtain the real server IP. Connect some IP addresses that are not servers to confuse the real IP

**Comment by dysf888** [comment]
> > I strongly recommended to remove the server IP display
> 
> The server IP is public knowledge, removing the display does nothing but make diagnosing peoples issues more difficult. Its trivial to retrieve that information with or without the display.
> 
> > add sending packets to random IP addresses
> 
> I'm not sure what you mean by this.

Some ways to prevent capturing packets to obtain the real server IP. Connect some IP addresses that are not servers to confuse the real IP

**Comment by TLeonardUK** [comment]
Writing relay software it outside the scope of this project. There are existing redirection services available that you can use for this.
