### ISSUE TITLE
Opening Loader.exe does nothing.

### ISSUE THREAD

**Issue by CenettDesign** [TLeonardUK/ds3os#14]
I followed the instructions to build the applications and everything seemed to work fine, I can run Server.exe with no problems, the server will start and operate as expected, but Loader.exe does nothing when I attempt to run it.

**Comment by Adephx** [comment]
My guess would be that you are missing dependencies? The Loader.exe should either be about 140MB in size or the folder should be full of files with reference paths.

**Comment by Jeyyu** [comment]
Sounds like u need to install net 5.0

**Comment by TLeonardUK** [comment]
So your building it yourself? Are you launching loader through visual studio then? If so do you not get an error somewhere?

**Comment by CenettDesign** [comment]
Downloading the binaries from releases fixed the problem, I was able to launch and use the Loader.exe from there. I'm not sure what happened with the build the first time, maybe something I messed up along the way.
