### ISSUE TITLE
Loader seems to install adware

### ISSUE THREAD

**Issue by scheffmr** [TLeonardUK/ds3os#149]
Hi,

today I decided to try ds3os, but when I start the loader my antivir detects an adware that seems to be connected to the loader: Win32/Contebrew.A!ml I downloaded it from the releases tab. Maybe check your code.

**Comment by Jeyyu** [comment]
#148

**Comment by TLeonardUK** [comment]
It definitely does not, view the issue Jeyyu posted for information, its a false positive.
