### ISSUE TITLE
Summon noob question

### ISSUE THREAD

**Issue by fervillano** [TLeonardUK/ds3os#15]
First I would like to say thanks, this is a great work and I hope you keep developing this, I'm noob in this types on things and I wanted to play with some friends with some mods without getting banned and this is the perfect way.

The question is if I can change the number of summons I can have in a world, like if i can have 8 guys playing on the same world.
I know little things, like the connection between the summons and the host is p2p. But I'm not sure if, with this "private" server, can I modify that limit.

I dont know if im explaining myself, English is not my primary language and I dont know a lot of DS3 server implementation or code.

Thanks for all seriously.

**Comment by TLeonardUK** [comment]
The client determines how many people can be summoned, the server just handles requests from the client fo find other people to summon,  it doesn't enforce any limit.

The Grand Archives cheat engine table has the ability to remove the summon limit if you wish to use that. 

I might add an option to do things like this to the launcher to save some time.

**Comment by fervillano** [comment]
Oh thanks for the rapid response, hope you stay doing great things like this, I will support it ^^
