### ISSUE TITLE
[BUG] Loader.exe marked as a trojan

### ISSUE THREAD

**Issue by btingle** [TLeonardUK/ds3os#155]
Recently I've been using ds3os to host a server with me and a couple friends, and has been working great so far. However, for some reason, now when I try to run Loader.exe windows tells me it is a virus, specifically Win32/Contebrew.A!ml. I couldn't find anything about this virus online, except that sometimes it is bundled with sketchy game downloads. Is this a mistake on window's part? If it really is a virus, then congrats because I allowed it so I can actually play the game with friends lol

**Comment by TLeonardUK** [comment]
See https://github.com/TLeonardUK/ds3os/issues/148 for more info. tl;dr - It's a heuristic based false positive, there isn't anything we can really do about it.
