### ISSUE TITLE
FDP error?

### ISSUE THREAD

**Issue by drahgon** [TLeonardUK/ds3os#158]
First time installing, friends used to work but now they dont. We all see the same error (FDP...). We are using Radmin to connect onto the server. Our host cant even open the server. The only thing we see is an error of FDP, any suggestions or links to this already being solved?

**Comment by drahgon** [comment]
i forgot to say but this also happens on other servers, and we also have cinders 2.15 installed

**Comment by TLeonardUK** [comment]
You are using mod engine which disable network play by default, there is a setting in the ModEngine ini file to re-enable it.
