### ISSUE TITLE
subtle bug in class NetIPAddress

### ISSUE THREAD

**Issue by KeithCoreDumped** [TLeonardUK/ds3os#166]
in
https://github.com/TLeonardUK/ds3os/blob/4f3c12e7dc21faebcaaebe680b3b48b2247943ea/Source/Server/Core/Network/NetIPAddress.h#L22
there are some typos in subscripts:
```cpp
Bytes[0] = 127;
Bytes[0] = 0;
Bytes[0] = 0;
Bytes[0] = 1;
```
should be:
```cpp
Bytes[0] = 127;
Bytes[1] = 0;
Bytes[2] = 0;
Bytes[3] = 1;
```
Though it may not cause problems, for now, it might bring about some difficulty in debugging someday if the default constructor is invoked.
Thanks for your awesome work by the way.

**Comment by TLeonardUK** [comment]
Good catch. It shouldn't cause any issue as nothing should rely on the default value of it, but I'll fix it anyway!

**Comment by TLeonardUK** [comment]
Very late fix, but resolved ...
