### ISSUE TITLE
Compatibility With Cinders

### ISSUE THREAD

**Issue by OkanSen** [TLeonardUK/ds3os#173]
Hi, 

This isn't an issue, but I didn't know where to ask this. Since the outage of servers, I took this as a chance to try out the Cinders mod, and I wanted to learn if your Multiplayer Mod is compatible with Cinders if I wanted to play online co-op with a friend.

Thanks in advance,
Props for the hard work!

**Comment by TLeonardUK** [comment]
DS3OS is mod agnostic. Its original intent was actually to help allow mods to run online without using the ban server :).

**Comment by OkanSen** [comment]
I understand, thanks for the very fast reply btw, and I'll test it out as soon as possible then!
