### ISSUE TITLE
Loader.exe with last Dark Souls III update gives "Executable not a recognised version" error

### ISSUE THREAD

**Issue by samshahw** [TLeonardUK/ds3os#175]
Dark Souls III + DLCs (genuine Steam copy)
App ver. 1.15.x
Regulation ver. 1.35
Error: "Executable not a recognised version"

**Comment by Grammernatzi** [comment]
Because it's a newer version. You need to downgrade to the last version to use Open Server, currently. [Here is info on how to do so.](https://wiki.speedsouls.com/darksouls3:Downpatching)

**Comment by luosuo3** [comment]
Is there any plan to update it for version 1.15

**Comment by Grammernatzi** [comment]
I mean, it just came out yesterday? Give it time.

**Comment by TLeonardUK** [comment]
Working on it. A lot of things have changed that I need to investigate, it will take a few days.

**Comment by TLeonardUK** [comment]
New version should now be compatible
