### ISSUE TITLE
unable to launch Game in Loader. "Executable not a recognised version"

### ISSUE THREAD

**Issue by ShoshoHrubblefongers** [TLeonardUK/ds3os#180]
![screenshot](https://user-images.githubusercontent.com/108223240/197910098-fd251534-178a-4927-981f-fc9f18d34028.png)

As you can see in my attachment screenshot, the exe location seems not to work. Also, the "Launch game" button is greyed out. Does it have something to do with my PC and game being Japanese? I live in Japan.

**Comment by TLeonardUK** [comment]
Yeh I think Japan gets a seperate exe to the rest of the world, I don't have a copy of that to test with I'm afraid.

**Comment by TLeonardUK** [comment]
Nothing much to do here unless I can get a JP exe so closed for now.
