### ISSUE TITLE
Executable not a recognised version after 1.15.2 patch

### ISSUE THREAD

**Issue by DenisNovac** [TLeonardUK/ds3os#183]
Patch 1.15.2 has come today
https://store.steampowered.com/news/app/374320/view/3656393454659154048?l=english

**Comment by TLeonardUK** [comment]
Yup I noticed. I'll hopefully have some free time this weekend to extract the new keys/offsets and update it.

**Comment by TLeonardUK** [comment]
This is going to take a bit of time. Looks like from have obfuscated all the code paths that I normally use to extract the keys/encrypted-block. 

I have the vague feeling they might have changed from TEA to encrypt the server-info block to something else.

Probably going to switch how we load the server info to a DLL so we can hook and replace the certificate/hostname in appropriate places. Will probably be more resiliant for any future updates as well.

**Comment by FracturedShader** [comment]
For anyone else coming here. In the interim, you can downgrade Dark Souls III to continue using ds3os. Found a quick guide on it here: https://www.makeuseof.com/how-to-downgrade-steam-games/

**Comment by TLeonardUK** [comment]
https://github.com/TLeonardUK/ds3os/releases/tag/v0.25.0.0-main

This should resolve the issue. Still prerelease at the moment, as the way it works has substantially changed.
