### ISSUE TITLE
[error]failed to spawn remote thread:GetLastError=0

### ISSUE THREAD

**Issue by EaEay** [TLeonardUK/ds3os#184]
![%MPPNQ%6 ~R2R4~YQ WHVEH](https://user-images.githubusercontent.com/124117231/215941359-ab4e6b48-3312-4a6a-9b32-592ddc06331b.jpg)
it happened when i tried to connect to the sesrver ds3os ,then i cannot launch any server.Seemed i am not the only one who have this problem.

**Comment by TLeonardUK** [comment]
Sorry for the late reply I didn't see this. Can you ask on the discord for help please, this is most likely down to unicode issues witht he path you are storing the game or launcher. It does not currently work well with unicode.
