### ISSUE TITLE
[SUGGESTION] Add button that copies over save file from retail

### ISSUE THREAD

**Issue by hax4dazy** [TLeonardUK/ds3os#185]
This might help out newer users copy over their save file. Could be done as a "first start" thing or something automatic

**Comment by TLeonardUK** [comment]
Good idea, I added a settings page and an option to do that to the loader.

![image](https://user-images.githubusercontent.com/18634751/226141078-cf3c98ac-63bd-4c6a-82ff-44485dfefa74.png)

**Comment by hax4dazy** [comment]
Thank you ❤️
