### ISSUE TITLE
The Server.exe is not opening

### ISSUE THREAD

**Issue by Ricc4rdo0107** [TLeonardUK/ds3os#187]
When I start the app it istantly crashes

**Comment by Ricc4rdo0107** [comment]
If I start in administrator mode it displays a prompt with the logo and then it crashes

**Comment by ItsZman2006** [comment]
I run into this issue all the time.  Try these things first.
1. Delete the database.sqlite file, then try rerunning the server. The database may have somehow gotten corrupted.
2. Delete config.json you may have an invalid character in there (iirc the server doesnt like asterisks in the information box)

If these didn't work. Redownload the server and redistribute the server.ds3osconfig file Note: Doing this will result in any bloodstains, messages, and ghost phantoms being completely wiped out
