### ISSUE TITLE
Unable to summon phantom

### ISSUE THREAD

**Issue by Sensoryy** [TLeonardUK/ds3os#19]
We were able to play together on server but after a while it started saying unable to summon phantom even with password and our hollowing level is too low to stop us from joining i think its a server issue. its not that we were banned either the boss in the areas we have tried are alive

**Comment by TLeonardUK** [comment]
That's unlikely to be an issue with the ds3os server. The dark  souls 3 server just acts as a matchmaking server, if you can see signs etc then it's doing its job. Connections between peers are p2p, if those are failing, then I'm guessing your using a dodgy steam emulator.

Do you have the log files for the server you were playing on?
