### ISSUE TITLE
failed to spawn remote thread:GetLastError=0

### ISSUE THREAD

**Issue by yangenpei** [TLeonardUK/ds3os#190]
![QQ截图20230415081354](https://user-images.githubusercontent.com/130305205/232173412-95ea5249-b8ed-45e3-a16f-6194d68d2a1b.jpg)
failed to spawn remote thread:GetLastError=0

**Comment by TLeonardUK** [comment]
This is likely due to using a non-ascii file path, if this occurs in future please try to provide more information.
