### ISSUE TITLE
DS3 Convergence Mod Private Server Crashes On Startup

### ISSUE THREAD

**Issue by Ryu776** [TLeonardUK/ds3os#191]
what was the solution to this? a friend of mine is having this exact issue. me and another friend have been playing fine for a few days and when we try to get our 3rd friend in now he starts having this issue. fire wall is disabled, antivirus doesn't pick it up, he's tried fresh installations for both the game and the mod and it still wont startup. it launches fine through steam but not through the server loader. i'm at a complete loss and i cant even get a solution from their discord.

_Originally posted by @Ryu776 in https://github.com/TLeonardUK/ds3os/issues/44#issuecomment-1528911380_

**Comment by Skullstompah** [comment]
I have the exact same issue, and the crashlog changes everytime but it consistently gives errors "487", "126" and "1114", I can open and play the mod from steam just fine, but for the life of me I cannot get it to work throught the loader.

**Comment by Skullstompah** [comment]
So, after lots of hours of work, I discovered the antivirus was blocking it, try adding an exception both to the loader.exe and DarkSoulsIII.exe
