### ISSUE TITLE
[BUG] Attempted retransmission of packet max number of times, assuming connection has died

### ISSUE THREAD

**Issue by WitchClaireBear** [TLeonardUK/ds3os#193]
I've setup and used the server properly before in the past. Coming back to the mod and attempting to play with the same people we've started receiving the following error: "Attempted retransmission of packet max number of times, assuming connection has died" followed by disconnecting the client. See image below.

![image](https://github.com/TLeonardUK/ds3os/assets/69371040/821976a1-ae62-4090-8270-6c12237e1571)

This error occurs after the player has connected to the server and someone is attempting to summon them as a co-op phantom. The initial warning message appears after confirming the summon but before the player actually appears in the game. The player is then in the game for about 30-60 seconds before being disconnected. I could be wrong but this seems like for some reason the message stream is closing early leading to the disconnect.

**Comment by ItsZman2006** [comment]
Does this happen on the latest build?

**Comment by WitchClaireBear** [comment]
We haven't encountered this issue since updating to the latest build.
