### ISSUE TITLE
Connection Severs on Area transitions?

### ISSUE THREAD

**Issue by ItsZman2006** [TLeonardUK/ds3os#194]
Hey! Don't know if you can do anything about this but there's an issue I experience where if the Host goes to another area in another players world (i.e., Host goes from Tower where the giant is to road of sacrifices) I get connection errored and sent back to my world.

Like I said I don't know if this is a server issue or if this is the game trying to remain sane with players but it's kind of annoying lol

Could you explain why this happens?

**Comment by TLeonardUK** [comment]
This is standard behaviour in the base game - road of sacrifices only supports one player. DS3OS doesn't change any of that behaviour.
