### ISSUE TITLE
[SUGGESTION] Have imported servers permanently stay saved

### ISSUE THREAD

**Issue by ItsZman2006** [TLeonardUK/ds3os#195]
There should be a feature where if you import a server it should stay saved in the server loader until its removed. This will make it easier and faster to get in game :D

**Comment by TLeonardUK** [comment]
FYI

Imported servers are deprecated in the next version of ds3os. They caused constant confusion and a lot of unneccessary support.

If anyone needs imported servers anymore they should use an older version.
