### ISSUE TITLE
disconnecting client as steam ticket authentication failed with error 4

### ISSUE THREAD

**Issue by An0tar** [TLeonardUK/ds3os#197]
i have this error during connecting to server every time. What i should do to repair it?

![image](https://github.com/TLeonardUK/ds3os/assets/105721680/67475da7-5836-4db2-8934-3f2bd08eb0fe)

**Comment by An0tar** [comment]
guys, i get it. ypu should just put 480 instead here instead other 
![image](https://github.com/TLeonardUK/ds3os/assets/105721680/6d6aef60-f803-4731-bfea-4581dce88fcf)

**Comment by TLeonardUK** [comment]
Piracy is not supported.
