### ISSUE TITLE
[Question] May I distribute this with mods I create?

### ISSUE THREAD

**Issue by ItsZman2006** [TLeonardUK/ds3os#198]
Hey! I was just wondering if I could distribute this server with my mod (Dark Souls III Coop Overhaul) so it is easier for the users of my mod to setup the mod and get ingame faster?

**Comment by TLeonardUK** [comment]
By all means, go for it.

This project is MIT licensed, you can do pretty much whatever you wish with it.

**Comment by ItsZman2006** [comment]
All right! Thank you so much! Closing issue now!
