### ISSUE TITLE
how to get save from server

### ISSUE THREAD

**Issue by 51nya51** [TLeonardUK/ds3os#201]
please say how to get save from server

**Comment by ItsZman2006** [comment]
Should be stored where your ds3 save data is.
Press Windows key + R and type the following into the box that pops up:
%Appdata%
In this newly opened window navigate to the Dark Souls III folder inside App Data. This will have a folder (or multiple) with multiple number names. This is the steam id of whatever account played the game. Search the folders until you find a .ds3os save file extension (iirc this is what gets created when you launch the game via ds3os launcher) Then you can rename this file's extension to .sl2 and you're good!
