### ISSUE TITLE
[BUG] Cannot launch DS2

### ISSUE THREAD

**Issue by ItsZman2006** [TLeonardUK/ds3os#202]
I can't load DS2, No matter what I try it just will not load... I got it to load the game a single time but that's it. I get this box then it just closes. Sometimes it'll open the game then immediately quit. This is done with a fresh valid steam copy on latest patch
![image_2024-01-01_224802942](https://github.com/TLeonardUK/ds3os/assets/105658225/8864f9f9-485c-4119-817c-7a822fa190af)

**Comment by TLeonardUK** [comment]
Yeh its a timing issue with steams drm changing the page protection. It will be fixed in the next prerelease.
