### ISSUE TITLE
Any plans for ds1 compatibility?

### ISSUE THREAD

**Issue by Unoaccaso** [TLeonardUK/ds3os#211]
Pretty self explanatory.

**Comment by TLeonardUK** [comment]
Not likely. PTDE doesn't use a central server, and Remastered uses a substantially different online protocol.

**Comment by M1sh2** [comment]
> Not likely. PTDE doesn't use a central server, and Remastered uses a substantially different online protocol.
Then what exactly is needed for ptde? After all, still need some kind of server for players to connect, even an intermediate like spacewar.

**Comment by TLeonardUK** [comment]
PTDE just uses steam lobbies for all the network connectivity, there is no central server that players connect to, it all goes through existing steam functionality.
