### ISSUE TITLE
Loader cannot import server configuration file

### ISSUE THREAD

**Issue by yuyuy005** [TLeonardUK/ds3os#213]
I want to LAN with my friends in Dark Souls 2 but the latest version cannot import the server configuration file as before. In future versions, can the import server configuration file function be re-added? Thank you for your work！

**Comment by TLeonardUK** [comment]
This what actually intentionally removed. The import feature was almost never used and just caused a lot of confusion and support requests from people.

If there are people actively using it, I may re-add it as some form of hidden/advanced option

**Comment by marcussacana** [comment]
So we are stuck on the master server?
