### ISSUE TITLE
What needs to be done to make the loader work in Linux under WINE\Proton-steam?

### ISSUE THREAD

**Issue by GreyStranik** [TLeonardUK/ds3os#217]
As far as I understand, when launched on the Steam Deck, it does not see that Steam is actually running. Is this true or am I wrong?
And will porting Loader to Linux help and what needs to be changed for this?

**Comment by R1D3R175** [comment]
Install Steam in the wine prefix, log in, should be opened in the background. 
Now launch Loader.exe from explorer.exe and it should work out of the box (I'm using wine-ge-8.26)

**Comment by Cloudef** [comment]
It's possible to also set env var "YES_STEAM_IS_RUNNING" to 1 on linux.

**Comment by MOOMAIV** [comment]
At least for ds2 you need this version https://github.com/TroncoNinja/ds3os-ds2wine-fix/tags
I had to install the windows version of steam in bottles and run it also with the dsos loader to get it working.
