### ISSUE TITLE
Linux Release v0.34.0.0-main is missing Loader folder

### ISSUE THREAD

**Issue by LuckyOwl1364** [TLeonardUK/ds3os#218]
Good morning! This seems like a fantastic work, y'all are heroes. However, when I downloaded the linux [release v0.34.0.0-main](https://github.com/TLeonardUK/ds3os/releases/tag/v0.34.0.0-main) it only contains the `README.txt` and the `Server` folder -- is that intentional?

**Comment by LuckyOwl1364** [comment]
It may be because DS3 isn't on linux (I was going to host a server on my linux machine but not play directly on it); the `Prerequisites` folder is also not present on linux, and I couldn't work out how to start a local server but that's on me and I didn't try that hard before switching to running it on windows (which worked fine). Very cool work y'all've done here!

**Comment by NoyingNabi** [comment]
Yeah, they have not ported this to linux, and as far as I know, they dont plan to either. You can have it work through proton, but for some reason the ds2 version does not work, the ds3 does so that is something.

**Comment by TLeonardUK** [comment]
The loader is only setup for windows. The linux build is only there for the actual server binary.

There was never really an expectation when I wrote this of people trying to run this on linux so it wasn't taken into account.

(Also sorry for the late reply, I've been busy and not paying much attention to github recently).

**Comment by LuckyOwl1364** [comment]
That's what I reckoned, and no worries about late reply! There wasn't much of anything actionable for this anyway :>
