### ISSUE TITLE
Cannot invade player if he is alone

### ISSUE THREAD

**Issue by Kyuhnaru** [TLeonardUK/ds3os#22]
Hi,

I'm playing with my friend on a custom server and I'm having trouble invading him.

I notice when he summon me for coop (_as an ally_), the server log says "**User is now invadable**"
and when I leave his world, the server log says "**User is now no longer invadable**".

![serverlog](https://user-images.githubusercontent.com/93096685/138609895-64ed5671-aa74-4369-8fc6-b80053f60047.png)

Does this mean you can only invade someone who is not alone ?
Is there a configuration option to make invasion possible even if the player is actually alone ?

Thank you.

**Comment by TLeonardUK** [comment]
The game sends messages to the server saying if the user is in a state capable of being invaded, if they are they are added to the pool of available targets.

There are a whole variety of reasons a user may be flagged as not invadable, invasion cooldowns, which area you are in, not-embered, etc.

DS3OS cannot effect the game from marking a user as uninvadable, as thats entirely done and enforced on the client-side.
