### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by tniromin** [TLeonardUK/ds3os#26]
2021-12-19 12:59:27 │ Warning │ Recieved error when trying to advertise server on master server. Response was not valid json.

**Comment by TLeonardUK** [comment]
That's not an error, just a warning. You can still connect to servers using the ds3osconfig files.

This is unreleased prototype software, I don't make any guarantees that servers will be up all the time.

**Comment by tniromin** [comment]
Got it.But y the warning really?

**Comment by TLeonardUK** [comment]
Because its useful to log things like that for debugging. If it was critical and would stop it functioning it would be shown as an error.
