### ISSUE TITLE
Login error in darksouls 3 client {with json error}

### ISSUE THREAD

**Issue by tniromin** [TLeonardUK/ds3os#28]
Darksouls launches from loader as intended to.
But doesnt connect to the given server {Lan}
Game version 1.15

**Comment by TLeonardUK** [comment]
You need to describe your issue better, I have no idea what your {lan} server is or how you have configured it.

**Comment by tniromin** [comment]
Oh sorry, I tried 0.7 and 0.6 releases under default setting.

**Comment by tniromin** [comment]
And the O/S was windows.

**Comment by tniromin** [comment]
I figured it out , was a problem in my directory.
