### ISSUE TITLE
Master Server Down

### ISSUE THREAD

**Issue by andrinoc1** [TLeonardUK/ds3os#29]
It's been two weeks or so.
When I try to  host my CMD prompt is filled with:
"CurrentDateAndTime │ Warning │                                     │ Recieved error when trying to advertise server on master server. Response was not valid json."

When I open the Loader I can't see any server up.

It's happening with me and a couple of friends, we were able to use the program before.

**Comment by TLeonardUK** [comment]
Please search issues before opening new ones, there are rather a few on this topic. 

Eg. https://github.com/TLeonardUK/ds3os/issues/26

This is expected, you can still connect to servers using the ds3osconfig files the server emits, as per the readme.

That log is just a warning, it's doesn't stop it working. 

This is unreleased prototype software, the master server isn't currently running on a permanent host at the moment so may come and go.

**Comment by andrinoc1** [comment]
I think you misunderstood me.
The program STOPPED WORKING after this error started showing up.
![image](https://user-images.githubusercontent.com/57641067/147154020-932af0d4-b0ac-4b3c-93ad-44a88d344aa8.png)

**Comment by TLeonardUK** [comment]
The master server doesn't do anything with regards to connecting to servers it just distributes the information that already exists in the ds3osconfig file. If your connection is failing to a server you are running you are likely using an out of date or incorrectly configured ds3osconfig file.

**Comment by andrinoc1** [comment]
Doesn't the server run with the default ds3osconfig file?

The only change I made was the name of the server and description.

**Comment by TLeonardUK** [comment]
My guess is the public or private host name is wrong in the config file your using. The public host name is what resolves to the ip address that people outside your lan connect to, the private host name is what is used for those inside your lan.

Easy way to test, set both to 127.0.0.1 if your running the server on your local machine and then import it and try to connect. If you can, that's the issue.

**Comment by andrinoc1** [comment]
Yeah, it was the Hostname.

Another thing, why can't I see other servers such as ?ServerName? 
I used to be able to see other servers, but since that issue it stopped happening.

**Comment by TLeonardUK** [comment]
That's expected. The automatic advertisement of servers is what the master server does, if its down you will only see ones you import yourself.

**Comment by andrinoc1** [comment]
Sad to know that the advertisement server is out. 

Anyway, great work, thanks for the quick response.

**Comment by TLeonardUK** [comment]
Shouldn't require anything else, mods should just work.
