### ISSUE TITLE
about nonsteam clients

### ISSUE THREAD

**Issue by Grabisoft** [TLeonardUK/ds3os#3]
Hi so far ive been testing the server with steam versions and it works.

My question is if this will ever support non steam versions of the game, since i think it will give the game a prolonged life making it independant from steam or from software servers.

so far, the server works fine with original copy of the game, but i wonder whats the point since you need steam, so why would people use this instead of the original normal server. not mentioning there is the risk of getting banned.

it would be nice to be able to use this with non steam copies. not relying at all with steam or anything else.

**Comment by TLeonardUK** [comment]
In theory it probably does work right now. 

However I will not be personally supporting non-steam clients, and likely will be adding steam-authentication later on. The main purpose of non-steam clients is piracy, which is not an area I have any interest in getting involved in.

That said, the code is MIT licensed, so people are free to do as they want with it.

As for what the main point is - I see a few benefits.

- Users are able to modify the rules of the game and in future will probably be able to distribute modded regulation files directly from the server.
- Those wanting an experience only with their friends have the choice to.
- Modded users can be segregated away from users who are running games incompatible with what they are running.
- Given the fairly rampant cheating that occurs in the retail server, this allows people to avoid some of the nastier hacks that are currently occuring.

In the end though this project is mainly being done as a hobby for my own curiosity, it doesn't ultimately need a point. 

Also I don't think there is actually any risk of getting banned on retail using this on its own, the only chance of getting banned is if you get yourself flagged using cheats on top of it.

**Comment by Adephx** [comment]
To be honest, I don't see a reason to limit non-steam clients, especially as ds3os wouldn't be supporting privacy directly, even if did support the Goldberg emulator. I was planning to play the Cinders mod with a couple of friends, one of which is particularly skittish about getting his Steam account flagged. DS3 is an old game at this point, which comes with heavy discounts (I think I purchased my version with all 2 DLC for less than 20€)

**Comment by Jeyyu** [comment]
Goldberg already works just like the original steam version. 

The chance of getting banned after this long of testing phase is rather unlikly tho, you can always create a dummy steam account and share your libary via family share.

**Comment by Adephx** [comment]
I wonder if the Cinders mode messed something up, because I get a "Failed to launch data souls 3 executable" warning, when I try to launch it. I will try the Vanilla version again and let you know.

**Comment by Jeyyu** [comment]
AFAIK, Cinder uses a modified version of the modengine, maybe they added some check to verify certain files. 
You could check Cinders Github and look it up, but then again original Steam version safes u a lot of time and possible headache.

**Comment by TLeonardUK** [comment]
As I said, I don't wish to support them. 

You're welcome to fork and support whatever other features you want though, its open source.

**Comment by Adephx** [comment]
Seems that my files were corrupted. Reinstalled the game from Steam, applied Goldberg emulator, works like a charm now.
