### ISSUE TITLE
Trying to launch via Proton, can't figure out how to launch game

### ISSUE THREAD

**Issue by cbacott** [TLeonardUK/ds3os#30]
I'm attempting to run this via Proton, so I can spin up a private coop server for my son and I. The server starts, though it complains that it's not getting valid json back from the master server. I assume it's working at least locally.

The loader comes up, and I imported the config from the server. I set the path to the Dark souls 3 exe, it says it's valid and detected Steam version. I can't figure out what to do next though? I am guessing the button on the bottom right is supposed to un-grey and let me launch the game using that?

![image](https://user-images.githubusercontent.com/19333095/147303665-986f7159-92fb-48c4-85c1-f6aec0bd420d.png)

Is there something I'm missing? I did install the prereq VSC++ runtime into this container as instructed.

I realize what I'm attempting here is completely unsupported, I'm just hoping that maybe there's some way to make this work via Proton. I'd like to play Cinders mod co-op with my son and not get him banned.

**Comment by TLeonardUK** [comment]
The button enables when it determines that steam is running and you are logged in, this is to prevent you trying to launch the game without being logged in, which causes a game restart and looses the patch that's made to the game during the initial launch.

It determines if you are logged in by checking some steam registry keys. I'm not sure how that would behave, or if the keys even exist under proton.

You can patch this check out reasonably easy if your reasonably familiar with code, just check the code for enabling that button in MainForm.cs. I can give you a patched version if you wish to try it, but it won't be till after the holidays.

**Comment by cbacott** [comment]
Yeah I was thinking it was something to do with Steam integration. I don't want to take up your time on that, it won't work as it's not going to find Steam API running under Windows, the wine layer is not going to be exposing that. 

I understand why you want to require the Steam auth, the only way to make this work under Proton is going to require disabling that portion of the code, or I think if it were rewritten to just be a DLL to chainload via modengine with an ini to configure it, and I won't ask you to go that far. 

Thanks for the reply, I don't think this will end up working for me.

**Comment by Cloudef** [comment]
Is it possible to do this checking some other way (e.g. steam api?) currently this makes loader.exe pain in linux as you would have to run steam through wine too.

**Comment by Sancoraa** [comment]
Works well with @Cloudef workaround, but now I can't get my controller to work.
On vanilla Dark Souls 3 my controller is only working using Steam's Big Picture controller support.
I tried to tweak some settings in Wine Control Panel and enabling Autoconfigure Joypads in Lutris to no avail

**Comment by twl-surrogate** [comment]
>  protontricks -c regedit.exe APPID-OF-DS3OS-LOADER
how do i get the appid of ds3os-loader ?
i run Loader.exe by adding it as a non-steam game and forcing Proton Experimental to be used on it, but i still can't launch the game

**Comment by Cloudef** [comment]
https://github.com/Matoking/protontricks#command-line
>
```
# Find your game's App ID by searching for it
protontricks -s <GAME NAME>
```

**Comment by twl-surrogate** [comment]
ok, i got the game to launch, though it acted like i launched DS3 for the 1st time and none of my existing saves are there, if i launch the game from steam normally it goes to offline mode and my saves are still there

**Comment by Cloudef** [comment]
It's because steam creates different proton prefix for different APPIDs you can copy the save from the DS3 prefix

**Comment by ThisNekoGuy** [comment]
> For now you can workaround this by doing: `protontricks -c regedit.exe APPID-OF-DS3OS-LOADER` browse to `HKEY_CURRENT_USER\SOFTWARE\Valve\Steam\ActiveProcess` and add `ActiveUser` DWORD key, set it to 1 Then add `PID` DWORD key and set it to 48, if 48 doesn't work run: `protontricks -c taskmgr.exe` and get some wine service PID, the PIDs usually don't change.

Changing the `PID` DWORD no l;onger works; it resets itself to 20, making this option not viable @Cloudef 
Even so, this regedit work isn't a **_real_** ideal compatibility solution
