### ISSUE TITLE
People outside my network can't connect to my server

### ISSUE THREAD

**Issue by hax4dazy** [TLeonardUK/ds3os#32]
OS: Windows 10 (21H2 19044.1415)
Game Version: Steam (1.15.0.0)
Mods: None
Ports forwarded: I opened all ports from 50000 - 50050 with UDP and TCP
Config file: [config.zip](https://github.com/TLeonardUK/ds3os/files/7800146/config.zip) (don't worry I removed any public IP's and stuff)

So basically I'm running into this issue where I can connect to my game server just fine by using a local IP, but as soon as I go past my router and my friend (who is outside my network) tries to connect it just dies and doesn't even ping the server once. 

I also tried multiple different solutions from inserting my local IP to using my public one to even using Hamachi and using their IP address but to no avail. I've taken extra care to make sure that I'm port forwarding this to the correct IP address and that I'm using the correct ports but nothing. Only when using Hamachi I got my friends client to connect _once_ but it just quickly connected to my client and then disconnected (or at least according to the console)

I got kinda confused by the JSON file and how I had to actually configure it because there's barely any documentation on what all the values do / how they could affect the game. 

I've also read thru the issues to see if they could fix my answer but none actually fixed the issue, I've tried multiple but to no avail

**Comment by hax4dazy** [comment]
I did some more testing today and found out another few things:

1. Compiled it myself to see if it was a problem with the latest release but it didn't do anything
2. The server doesn't like it when you change the ports
3. Tripple checking the open ports on my router did nothing
4. Local connection doesn't work any more 
5. There's no code for the "master server" so I would not know if it would run even with it there or not.

**Comment by hax4dazy** [comment]
Hey thanks for your amazing reply! 

I've both used the site you recommended to me and scanned my own network while using a VPN with nmap and both said the port is either filtered or just closed. This is kinda confusing to me because I clearly opened the ports on my router.

I tried changing the port and it still doesn't wanna connect. For the log, all it said was "STEAMID has connected" and then 3 seconds afterwards "STEAMID has disconnected" or at least that's what I remember from it. 

I've also made 300% sure that the app isn't getting blocked by my windows firewall so that's also no issue.

Have you got anything else I could try out? At this point I'm all out of ideas and I'm thinking maybe hosting it on something like docker and running it on a whole different machine to test if that would work. (not a bad idea actually, i'll look into that a bit more).

**Comment by hax4dazy** [comment]
Adding onto this: Just did some quick testing with running the local server and then using either my local IP or just the loopback IP and none work when the ports are changed.

For reference this is what I changed the ports to: 
`2022-01-06 01:03:07 │ Log     │                                     │ Login service is now listening on port 16386.
2022-01-06 01:03:07 │ Log     │                                     │ Auth service is now listening on port 16384.
2022-01-06 01:03:07 │ Log     │                                     │ Game service is now listening on port 16385.`

**Comment by hax4dazy** [comment]
Tried running it on an entirely different device and with the default ports the local connection works, but my friend still couldn't connect. Changing the ports makes it so I can't even connect any more. On the other port the server does respond to pings from the site you said to test my ports with. I'm like 300% out of ideas, at this point I'm thinking my router has an issue with me opening those specific ports to the outside and that's why it doesn't like anyone connecting.

**Comment by hax4dazy** [comment]
I'm going to close this here. I think its my router somehow still blocking the ports even tho they are open? I'll try to see if I can host the server outside of my network to confirm its my network being garbage and not allowing any connections thru the ports. 

Anyways thanks for your amazing support on this project ❤️

**Comment by AtilioA** [comment]
I have the same problem and have gone through the same troubleshooting, except I managed to make it work before and now I just can't.

**Comment by AtilioA** [comment]
@hax4dazy could you check your WAN IP from your router's config page? I found out that, in my case, it was different from the public IP displayed by services outside of my network, thus not making it possible to use it as a server hostname. After reconfiguring my router, I was able to get the same IP; seems like I had messed something on my router or my ISP uses some weird CGN. Just my two cents.

**Comment by hax4dazy** [comment]
While it was the case for your issue, I'm about 100% sure I've got the right IP address here. I run a lot of services on my network and most of them need to be directly pointed towards my IP address to function. Thanks for thinking with me tho ❤️
