### ISSUE TITLE
Master server is not work 

### ISSUE THREAD

**Issue by saswas228** [TLeonardUK/ds3os#33]
I already realized that the server does not always work, the problem is that while it does not work, I cannot play on the server with a friend, what ip we would not enter in the config, can I download the master server somewhere so that I myself can support it ?

**Comment by TLeonardUK** [comment]
Please look through the bunch of other closed issues regarding this, the master server isn't required in any way for connections.

https://github.com/TLeonardUK/ds3os/issues?q=is%3Aissue+is%3Aclosed

Side note the master server code is available here: https://github.com/TLeonardUK/ds3os/tree/main/Source/MasterServer
