### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by saswas228** [TLeonardUK/ds3os#34]
Thanks for the prompt response to the previous call, I get the following error when compiling 
![image](https://user-images.githubusercontent.com/97042559/148088944-04d1f479-2e1c-4ec5-ae1f-6d4e617bf97a.png)
Pls help me.

**Comment by saswas228** [comment]
My OC config: 
![image](https://user-images.githubusercontent.com/97042559/148089194-dd8e2011-0724-465a-a7d2-16b3bcfee9be.png)

**Comment by TLeonardUK** [comment]
Get latest, your using an old version with something that was fixed a while ago in it.

**Comment by saswas228** [comment]
This works, thank you very much.
