### ISSUE TITLE
Question on the MatchMaking System

### ISSUE THREAD

**Issue by saswas228** [TLeonardUK/ds3os#35]
In the game there is a restriction on the orders of weapons and a level, is it possible to configure the server config to disable these restrictions that, for example, 200 LVL could be renewed to 1. I know that with the help of a red chalk and password, this restrictions can be bypassed, but it is interesting to me exactly the invasion of Random players with a red eye. I noticed that in the config there are lines responsible for the balance and conducted monipulations with them, but the results did not give it, so I ask to help explain about the omniscient)

**Comment by Jeyyu** [comment]
There are 2 options called "DisableLevelMatching" and "DisableWeaponLevelMatching".

Is this what you are looking for?

**Comment by TLeonardUK** [comment]
What @Jeyyu said, those flags should disable level matching.

Be aware this doesn't disable any of the other matching mechanics - like cooldown between invasions. Thats entirely handled by the client and something DS3OS has no way to effect.

**Comment by saswas228** [comment]
I tried to change this line earlier, I will try again and report the result.

**Comment by saswas228** [comment]
I checked that this does not disable the matchmaking system, which means it is tied to the client itself or there are some other conditions.

**Comment by saswas228** [comment]
Really works, but when intruding, the phantom does not become weaker in accordance with the host, and when invading 131 lvl to 20 I feel uncomfortable, is it possible to somehow disable the selection of games but leave the balancer?

**Comment by TLeonardUK** [comment]
The way matching works is the client requests a list of currently available invasion targets, which the server returns, filtered by levels criteria. The server doesnt effect balancing in any way, that's entirely client side. It might very well be that the balancing code do L9esn't expect to handle such huge level differences and behaves poorly. Nothing that can be directly done about that unfortunantely, not without modifying the client.

**Comment by saswas228** [comment]
You said everything correctly, but I would like to ask you to implement the balance system in the future. when using a red crayon and a password to view it, the character becomes the same level as the player who called him, if this rule was done by all other methods of calling, then everything will work.

**Comment by Jeyyu** [comment]
Afaik this is not possible from the server alone, everyone on the server would need to install some mod on the client side. (besides the fact that the mod itself first need to be created)

Only option I could think of is maybe to only allow a certain level to be matched or only if they are the same level, but then again its not exactly what you want
