### ISSUE TITLE
[Feature] Build for Linux?

### ISSUE THREAD

**Issue by khionu** [TLeonardUK/ds3os#36]
If this could be built for Linux, it would make administration a lot easier. Happy to collaborate if need be!

**Comment by TLeonardUK** [comment]
It should be relatively painless to get ir running on Linux, there isn't much about it that is Windows specific. Some cmake files will probably need to replace the vs solutions and removing the use of vcpkg. The socket code at the moment is about the only code that is windows specific, and that should be trivial to convert over to standard bsd sockets.

Feel free to give it a go if you want, I'll have a look into it when I have some time.

**Comment by GrimKriegor** [comment]
Thank you for working on this project and making it libre!
Good to see the influx of users during this retailpocalypse ahah.

I have been casually looking into getting the server component building with CMake.
Here is the dependency list, from what I could gather, for reference;

- [BrianGladman's aes](https://github.com/BrianGladman/AES)
- [BrianGladman's aes_modes](https://github.com/BrianGladman/modes)
- [nlohmann's json](https://github.com/nlohmann/json) (3.10.0) (include/nlohmann/json.hpp only)
- curl
- openssl
- protofbuf (2.6.1rc1)
- sqlite3 (3.36.0)
- steamworks_sdk (1.51)
- zlib (1.2.11)

**Comment by intrand** [comment]
Once building on Linux (if/when), containerizing the different components would make for really easy deployment for those of us with docker/kubernetes/nomad/whatever.

**Comment by IceDBorn** [comment]
Does the loader work with proton (I haven't tried launching it yet)? A linux version of the loader would be nice too.

**Comment by TLeonardUK** [comment]
You can probably run it under wine, the way it detects if your signed into steam almost certainly won't work though (reading various registry keys), so that would probably need to be stripped out or changed.

**Comment by GrimKriegor** [comment]
I can't test launching/patching the game thru Wine, but the loader does run on vanilla Wine, lists the servers, and once you launch Steam inside that same WinePrefix, the button switches from `Not logged into Steam` to `Launch Game`, so its promising!

**Comment by IceDBorn** [comment]
> I can't test launching/patching the game thru Wine, but the loader does run on vanilla Wine, lists the servers, and once you launch Steam inside that same WinePrefix, the button switches from `Not logged into Steam` to `Launch Game`, so its promising!

Do I have to install the windows version of steam inside the prefix?

**Comment by GrimKriegor** [comment]
> Do I have to install the windows version of steam inside the prefix?
I am thinking that maybe it will work if you run the launcher inside the same Proton prefix the game will use, if at all possible.

**Comment by khionu** [comment]
> You can probably run it under wine, the way it detects if your signed into steam almost certainly won't work though (reading various registry keys), so that would probably need to be stripped out or changed.

Whatever games normally do should work, but there should be a way. That said, maybe it'd be better to just proxy, and have the proxy frame the requests? Could modify hosts in order to make it use the proxy, and the proxy can be managed through what is currently the launcher

**Comment by IceDBorn** [comment]
Does anyone know the IP the game tries to connect to?

**Comment by GrimKriegor** [comment]
Unfortunately, I don't think its that simple.
From what I could gather the game has some public keys hardcoded into it, the launcher component patches them and the matchmaking server address while launching the game.

**Comment by IceDBorn** [comment]
> 

What is the server address though?

**Comment by IceDBorn** [comment]
What is the server address though?

**Comment by TLeonardUK** [comment]
Are you asking what the retail server address is? Its fdp-steam-ope-login.fromsoftware-game.net, what address is used for launching a custom server depends entirely on which one is launched.

**Comment by GrimKriegor** [comment]
I think this might be it `fdp-steam-ope-login.fromsoftware-game.net`.
Behold the warning tho, not sure if there are consequences for mismatching the keys.
Source:
https://github.com/TLeonardUK/ds3os/blob/main/Config/retail.ds3osconfig

**Comment by IceDBorn** [comment]
I'll try redirecting the address using the hosts file and I'll report back soon.

**Comment by IceDBorn** [comment]
I tried removing steam's check and launching the game but it does not work.

**Comment by cbacott** [comment]
> I tried removing steam's check and launching the game but it does not work.

I'm not 100% certain here, but from my experience in Linux, patching memory addresses in Wine just does not work right. Things like Cheat Engine and other launchers I've tried for other games that work via memory manipulation like how this launcher works do not work under the Wine(Proton) environment. The only successful way to accomplish what this launcher is trying to do, under Linux, would be the convert the memory patching to a dll hack like most Dark Souls mods operate, possibly having the DLL read the parameters from a text file for the server chosen, and have the Launcher application simply write/modify that text file.

**Comment by TLeonardUK** [comment]
Just been looking at your branch @GrimKriegor, just as an FYI be careful with making the third party dependencies submodules of the original repos. Ds3 uses a modified version of the CWC algorithm from the original repo, so there are local changes to its source.

**Comment by GrimKriegor** [comment]
@TLeonardUK thanks for the heads up!

The message on commit https://github.com/TLeonardUK/ds3os/commit/11e164fd204267c200921c1542408ff10fc813fe made me aware of that possibility, not only for `aes_modes`, but also for the others.
I see the changes to `cwc.c` from `aes_modes` in https://github.com/TLeonardUK/ds3os/commit/9e085bb21b74fb32b8635784ea1a15fb86a73e40#diff-58e2f8df321873b9b75648da0163976b061c44bb5539a12e94eaf3b5e0881021
I also see changes to other dependencies' project files, namely in `Source/ThirdParty/protobuf-2.6.1rc1/vsprojects/libprotobuf-lite.vcxproj`.
Gonna have to keep these in mind in order not to break the original build flow, ahah.

The submodules were so that I can more easily see the differences from upstream and backport any existing CMake support.

Regardless, consider this a research experiment, you may prefer to bundle the dependencies into this repo instead of maintaining separate forks, and I am not here to mess with that workflow.

**Comment by garyttierney** [comment]
Here's a working CMake build: https://github.com/garyttierney/ds3os/commit/feac74cb7dc84a87e96616f1af81a411f071276c. `cmake-converter` was used as a base, so still a bit of a rough draft and it leaves the VS build broken. Consider it still WIP.

Most dependencies are retrieved from vcpkg again, so you'll have to pass CMAKE_TOOLCHAIN_FILE to build it. As a result of that protobuf has been updated to the latest available from vcpkg ports. There's a comment that alludes to requiring protobuf-2.6rc1, but that hasn't been my experience. Is there something specific that breaks under newer protobuf @TLeonardUK?

**Comment by TLeonardUK** [comment]
@garyttierney I suspect it should be fine as long as you don't jump a major version on protobuf. I kept to that version purely because its the one that DS3 uses and seemed safest for compatibility.

**Comment by garyttierney** [comment]
FWIW, no issues here on 3.18.0.

**Comment by GrimKriegor** [comment]
It seems [protobuf version 2.7.0](https://github.com/protocolbuffers/protobuf/tree/2.7.0), is the one which introduces CMake support, migrating to it (+1 minor version) or backporting the CMake files are two possible options moving forward.

**Comment by garyttierney** [comment]
[This branch](https://github.com/garyttierney/ds3os/tree/feat/buildsys-cmake) gets as far as linking on Fedora with GCC 12, but fails due to a few missing symbols in AES-CWC. Probably needs some export attributes updated or something.

**Comment by GrimKriegor** [comment]
Awesome progress @garyttierney! Thanks for working on this.
Is the CMake recipe for the `unofficial-sqlite3` module missing in that branch?

**Comment by garyttierney** [comment]
You'll want to use the vcpkg CMake toolchain, e.g.

```shell
> $ git clone git@github.com:garyttierney/ds3os.git --branch feat/buildsys-cmake
> $ git clone git@github.com:Microsoft/vcpkg.git
> $ mkdir build && cd build
> $ cmake -DCMAKE_TOOLCHAIN_PATH=$(pwd)/../vcpkg/scripts/buildsystems/vcpkg.cmake ..
```

If the other ones were working it's probably found them already installed by your systems package manager.

**Comment by garyttierney** [comment]
Probably a few runtime issues to sort out, but:
```
[gtierney@DESKTOP-3IGUISH Server]$ uname -a
Linux DESKTOP-3IGUISH 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[gtierney@DESKTOP-3IGUISH Server]$ ./Server
2022-01-29 23:22:00 � Log     �                                     �     ____             __      _____             __        _____
2022-01-29 23:22:00 � Log     �                                     �    / __ \____ ______/ /__   / ___/____  __  __/ /____   |__  /
2022-01-29 23:22:00 � Log     �                                     �   / / / / __ `/ ___/ //_/   \__ \/ __ \/ / / / / ___/    /_ <
2022-01-29 23:22:00 � Log     �                                     �  / /_/ / /_/ / /  / ,<     ___/ / /_/ / /_/ / (__  )   ___/ /
2022-01-29 23:22:00 � Log     �                                     � /_____/\__,_/_/  /_/|_|   /____/\____/\__,_/_/____/   /____/
2022-01-29 23:22:00 � Log     �                                     �   / __ \____  ___  ____     / ___/___  ______   _____  _____
2022-01-29 23:22:00 � Log     �                                     �  / / / / __ \/ _ \/ __ \    \__ \/ _ \/ ___/ | / / _ \/ ___/
2022-01-29 23:22:00 � Log     �                                     � / /_/ / /_/ /  __/ / / /   ___/ /  __/ /   | |/ /  __/ /
2022-01-29 23:22:00 � Log     �                                     � \____/ .___/\___/_/ /_/   /____/\___/_/    |___/\___/_/
2022-01-29 23:22:00 � Log     �                                     �     /_/
2022-01-29 23:22:00 � Log     �                                     �
2022-01-29 23:22:00 � Log     �                                     � https://github.com/tleonarduk/ds3os
2022-01-29 23:22:00 � Log     �                                     �
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Loaded '/home/gtierney/.local/share/Steam/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 374320
2022-01-29 23:22:00 � Log     �                                     � Initializing server ...
2022-01-29 23:22:00 � Log     �                                     � Loaded rsa key pair successfully.
2022-01-29 23:22:00 � Log     �                                     � Public ip address: 86.22.222.71
2022-01-29 23:22:00 � Log     �                                     � Private ip address: 1.1.0.127
2022-01-29 23:22:00 � Log     �                                     � Opened sqlite database succesfully.
2022-01-29 23:22:00 � Log     �                                     � Login service is now listening on port 50050.
2022-01-29 23:22:00 � Log     �                                     � Auth service is now listening on port 50000.
2022-01-29 23:22:00 � Log     �                                     � Game service is now listening on port 50010.
2022-01-29 23:22:01 � Success �                                     � Server is now running.
```

**Comment by GrimKriegor** [comment]
Great work!
And indeed, seems I was misusing vcpkg.
After fixing some file paths (https://github.com/garyttierney/ds3os/pull/1) I too was able to build on Arch.
However I am segfaulting on startup, will try to figure out whats wrong, could be an issue with my environment.
```
Linux hylek 5.15.12-gnu-1 #1 SMP PREEMPT Tue, 04 Jan 2022 00:38:58 +0000 x86_64 GNU/Linux

2022-02-01 20:27:32  Log                                               ____             __      _____             __        _____
2022-02-01 20:27:32  Log                                              / __ \____ ______/ /__   / ___/____  __  __/ /____   |__  /
2022-02-01 20:27:32  Log                                             / / / / __ `/ ___/ //_/   \__ \/ __ \/ / / / / ___/    /_ <
2022-02-01 20:27:32  Log                                            / /_/ / /_/ / /  / ,<     ___/ / /_/ / /_/ / (__  )   ___/ /
2022-02-01 20:27:32  Log                                           /_____/\__,_/_/  /_/|_|   /____/\____/\__,_/_/____/   /____/
2022-02-01 20:27:32  Log                                             / __ \____  ___  ____     / ___/___  ______   _____  _____
2022-02-01 20:27:32  Log                                            / / / / __ \/ _ \/ __ \    \__ \/ _ \/ ___/ | / / _ \/ ___/
2022-02-01 20:27:32  Log                                           / /_/ / /_/ /  __/ / / /   ___/ /  __/ /   | |/ /  __/ /
2022-02-01 20:27:32  Log                                           \____/ .___/\___/_/ /_/   /____/\___/_/    |___/\___/_/
2022-02-01 20:27:32  Log                                               /_/
2022-02-01 20:27:32  Log
2022-02-01 20:27:32  Log                                           https://github.com/tleonarduk/ds3os
2022-02-01 20:27:32  Log
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Loaded '/home/grim/.local/share/Steam/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
2022-02-01 20:27:32  Error                                         Failed to initialize steam game server api.
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
assert_20220201202732_10.dmp[3772094]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220201202732_10.dmp
[1]    3772084 segmentation fault (core dumped)  ./Server
```

**Comment by khionu** [comment]
I can edit the OP to make this a tracking issue, or maybe we could create a new issue and leave this as a discussion thread? Either way, I think we should have progress tracked more than just as comments in a thread

**Comment by garyttierney** [comment]
> Great work! And indeed, seems I was misusing vcpkg. After fixing some file paths ([garyttierney#1](https://github.com/garyttierney/ds3os/pull/1)) I too was able to build on Arch. However I am segfaulting on startup, will try to figure out whats wrong, could be an issue with my environment.
> 
> ```
> Linux hylek 5.15.12-gnu-1 #1 SMP PREEMPT Tue, 04 Jan 2022 00:38:58 +0000 x86_64 GNU/Linux
> 
> 2022-02-01 20:27:32  Log                                               ____             __      _____             __        _____
> 2022-02-01 20:27:32  Log                                              / __ \____ ______/ /__   / ___/____  __  __/ /____   |__  /
> 2022-02-01 20:27:32  Log                                             / / / / __ `/ ___/ //_/   \__ \/ __ \/ / / / / ___/    /_ <
> 2022-02-01 20:27:32  Log                                            / /_/ / /_/ / /  / ,<     ___/ / /_/ / /_/ / (__  )   ___/ /
> 2022-02-01 20:27:32  Log                                           /_____/\__,_/_/  /_/|_|   /____/\____/\__,_/_/____/   /____/
> 2022-02-01 20:27:32  Log                                             / __ \____  ___  ____     / ___/___  ______   _____  _____
> 2022-02-01 20:27:32  Log                                            / / / / __ \/ _ \/ __ \    \__ \/ _ \/ ___/ | / / _ \/ ___/
> 2022-02-01 20:27:32  Log                                           / /_/ / /_/ /  __/ / / /   ___/ /  __/ /   | |/ /  __/ /
> 2022-02-01 20:27:32  Log                                           \____/ .___/\___/_/ /_/   /____/\___/_/    |___/\___/_/
> 2022-02-01 20:27:32  Log                                               /_/
> 2022-02-01 20:27:32  Log
> 2022-02-01 20:27:32  Log                                           https://github.com/tleonarduk/ds3os
> 2022-02-01 20:27:32  Log
> dlopen failed trying to load:
> steamclient.so
> with error:
> steamclient.so: cannot open shared object file: No such file or directory
> [S_API] SteamAPI_Init(): Loaded '/home/grim/.local/share/Steam/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
> 2022-02-01 20:27:32  Error                                         Failed to initialize steam game server api.
> src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
> src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
> assert_20220201202732_10.dmp[3772094]: Uploading dump (out-of-process)
> /tmp/dumps/assert_20220201202732_10.dmp
> [1]    3772084 segmentation fault (core dumped)  ./Server
> ```

Looks like you forgot to create steam_appid.txt

**Comment by garyttierney** [comment]
> I can edit the OP to make this a tracking issue, or maybe we could create a new issue and leave this as a discussion thread? Either way, I think we should have progress tracked more than just as comments in a thread

I'll open a PR with my change set and we can continue tracking progress there

**Comment by khionu** [comment]
Well, I was also thinking of said tracking issue covering Wine usage, but that is a good start

**Comment by garyttierney** [comment]
Ah, I see. Yeah a separate issue for tracking that would be good then. I didn't plan on doing that in my tree.

**Comment by ogdenwebb** [comment]
> I can't test launching/patching the game thru Wine, but the loader does run on vanilla Wine, lists the servers, and once you launch Steam inside that same WinePrefix, the button switches from `Not logged into Steam` to `Launch Game`, so its promising!

@GrimKriegor which version of Wine did you use in this case?

**Comment by Cloudef** [comment]
https://github.com/TLeonardUK/ds3os/issues/30#issuecomment-1038068886 see this workaround for proton / linux steam

**Comment by GrimKriegor** [comment]
@ogdenwebb `wine-7.0-rc5` it seems.
@Cloudef 's method looks promising.

**Comment by Jokler** [comment]
@cbacott I was able to connect to a server with steam under wine and `cap_sys_ptrace` set so it definitely works.
I haven't tested the details too much but if it helps this was the command I used to make it work (through winesteam in lutris):
```sh
sudo -E capsh --caps="cap_setpcap,cap_setuid,cap_setgid+ep cap_sys_ptrace+eip" --keep=1 --user="$USER" --addamb="cap_sys_ptrace" --shell=/usr/bin/lutris --
```

**Comment by Cloudef** [comment]
Weird, the launcher works for me without any capabilities. Are you running SELinux or something? The launcher does not use ptrace at all so you should not need it :/

**Comment by Jokler** [comment]
I tested on some random server and I was unable to connect so I just assumed that they were right about it not working. Looking at the wine code I am not sure how it works if not with ptrace. Is it because both programs are child processes of wine?

Either way I tested it again, this time against my own server and it definitely just works as long as you can get the loader to detect steam one way or another.

**Comment by dysf888** [comment]
Urgently, we urgently need the Linux version of the server. Recently, we suffered DDoS attacks. The Windows version of the server is more expensive. Using Linux can make us more money to increase defense

**Comment by clague** [comment]
https://github.com/clague/ds3os-loader-rs/

Here is a WIP loader for linux.

**Comment by dysf888** [comment]
> You'll want to use the vcpkg CMake toolchain, e.g.
> 
> ```shell
> > $ git clone git@github.com:garyttierney/ds3os.git --branch feat/buildsys-cmake
> > $ git clone git@github.com:Microsoft/vcpkg.git
> > $ mkdir build && cd build
> > $ cmake -DCMAKE_TOOLCHAIN_PATH=$(pwd)/../vcpkg/scripts/buildsystems/vcpkg.cmake ../ds3os
> ```
> 
> If the other ones were working it's probably found them already installed by your systems package manager.
How to solve this
CMake Error at Source/Server/CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by
  "unofficial-sqlite3" with any of the following names:

    unofficial-sqlite3Config.cmake
    unofficial-sqlite3-config.cmake

  Add the installation prefix of "unofficial-sqlite3" to CMAKE_PREFIX_PATH or
  set "unofficial-sqlite3_DIR" to a directory containing one of the above
  files.  If "unofficial-sqlite3" provides a separate development package or
  SDK, be sure it has been installed.

**Comment by dysf888** [comment]
> ```shell
> cmake -DCMAKE_TOOLCHAIN_PATH=$(pwd)/../vcpkg/scripts/buildsystems/vcpkg.cmake ../ds3os
> ```


When I succeed in cmake, execute make and report an error
[  1%] Generating aes_amd64.o
/bin/sh: 1: YASM_EXE-NOTFOUND: not found
make[2]: *** [Source/ThirdParty/aes_modes/CMakeFiles/aes_modes.dir/build.make:62: Source/ThirdParty/aes_modes/aes_amd64.o] Error 127
make[1]: *** [CMakeFiles/Makefile2:208: Source/ThirdParty/aes_modes/CMakeFiles/aes_modes.dir/all] Error 2

**Comment by Cloudef** [comment]
You are missing yasm assembler.

**Comment by dysf888** [comment]
> yasm assembler
Thank you for answering my question

Yes, but yasm only supports windows. I try to compile under Ubuntu and want a server that can run on Linux
 @Cloudef

**Comment by dysf888** [comment]
> You are missing yasm assembler.

thanks

**Comment by dysf888** [comment]
> * steamworks_sdk

With your help, I successfully compiled the server, but the operation reported an error. Do you know how to solve the problem of SDL




2022-03-25 13:33:46 � Log � � Login service is now listening on port 50050.

2022-03-25 13:33:46 � Log � � Auth service is now listening on port 50000.

2022-03-25 13:33:46 � Log � � Game service is now listening on port 50010.

2022-03-25 13:33:46 � Success � � Server is now running.

Warning: failed to init SDL thread priority manager: SDL not found

**Comment by khionu** [comment]
I was eager to host my own DS3 server before, but given the chatter, I think it's likely that all of DS games are going to be getting EAC. Unsure how viable this project will be then.

**Comment by Grammernatzi** [comment]
This will likely work fine even if EAC gets added, because EAC can just be disabled.

**Comment by TLeonardUK** [comment]
Initial support for linux is now in mainline. Check out my comments on https://github.com/TLeonardUK/ds3os/pull/74 for further details.

**Comment by TLeonardUK** [comment]
Closing as functional, further work should be added as new issues.
