### ISSUE TITLE
about private server

### ISSUE THREAD

**Issue by jonysky** [TLeonardUK/ds3os#39]
Hello, author, I am very excited to see your project, my friends and I want to play Dark Souls through private server, and we have an idle server,maybe not big, but enough for 2-3 person you know.  I would like to ask what we need to change in the project if we want to use our own server, hope to get your reply.

**Comment by TLeonardUK** [comment]
Can you elaborate? I'm not sure what you are trying to ask.

**Comment by jonysky** [comment]
> Can you elaborate? I'm not sure what you are trying to ask.

thank you! i think i already find out some question,but i still want to know how to set the password, i didn't find that?

**Comment by TLeonardUK** [comment]
Its set in Saved\config.json, search for password.

**Comment by jonysky** [comment]
> Its set in Saved\config.json, search for password.

why play counter in my server is "not advertised", and sometimes i can't delete the server. what happen?

**Comment by TLeonardUK** [comment]
I'm not entirely sure what you mean. If your server isn't advertised you don't need to set a password. The password is just to stop people joining via the launcher list.

**Comment by jonysky** [comment]
> I'm not entirely sure what you mean. If your server isn't advertised you don't need to set a password. The password is just to stop people joining via the launcher list.

yes, i know how to set a password now, but i want to ask that play counter in my server is "not advertised.

![1111](https://user-images.githubusercontent.com/46805300/150954003-11359dc0-741a-4ce2-830d-51c3f8c033ed.png)

and my friend can't enter my server

**Comment by TLeonardUK** [comment]
Its set to not advertised because you aren't advertising it on the master server, which is where it gets player information from, it doesn't query servers directly.

Side note having a password is pointless if its not advertised, the password is just for joining via the master-server listing.

As for why your friend can't enter, you need to give more information about why. Ensure you followed the information in the FAQ in the readme as well.

https://github.com/TLeonardUK/ds3os

**Comment by jonysky** [comment]
> Its set to not advertised because you aren't advertising it on the master server, which is where it gets player information from, it doesn't query servers directly.
> 
> Side note having a password is pointless if its not advertised, the password is just for joining via the master-server listing.
> 
> As for why your friend can't enter, you need to give more information about why. Ensure you followed the information in the FAQ in the readme as well.
> 
> https://github.com/TLeonardUK/ds3os

can you give me some reason why i am not advertising it on the master server?
![22222](https://user-images.githubusercontent.com/46805300/150961581-2b09c8ea-d035-4af5-a8e9-8576e125a731.png)
i think i modify all the things, and the server are running, i can enter my own server, but still "not advertised"

**Comment by TLeonardUK** [comment]
Because the server on your list is from you importing a config file, these are implicitly not advertised.

Delete the server in the list, ensure Advertise is set to true in Saved/config.json and it should be advertised and show in the list normally.
