### ISSUE TITLE
SignManager::Handle_RequestSummonSign sometimes throws exception

### ISSUE THREAD

**Issue by stosSe4r** [TLeonardUK/ds3os#41]
At SignManager.cpp@317, 
```cpp
Ensure(OriginClient != nullptr); // Should always be valid if the sign is in the cache.
```
I find the server occasionally crashes because of an uncaught exception on this line.
I guess this might be caused by some state transition failure, or because of broken network.
Is it OK to remove this assertion and return MessageHandleResult::Error instead?

**Comment by TLeonardUK** [comment]
The assertion is correct. If the client has been disconnected or otherwise lost their signs should have been removed from the cache in SignManager::OnLostPlayer, and the code shouldn't get to that assert. So for some reasons we have some signs not being removed from the cache correctly.

**Comment by TLeonardUK** [comment]
Should be fixed on latest. Some operations were running out of expected order.
