### ISSUE TITLE
[BUG] DS3 Convergence crash on start

### ISSUE THREAD

**Issue by NaliAroni** [TLeonardUK/ds3os#44]
I'm trying to log into a friend's server with the Convergence mod active. DS3 will start with a white screen for 3 seconds, turn black for 2 seconds, then crash. During this time the DS3 cursor is displayed  Its not happening on the vanilla copy. 
The confusing thing is, that several other friends are able to connect with Convergence just fine. DS3 starts just fine when launched normally. 

Which log files should I send?

Any help in this matter will be greatly appreciated especially since the fromsoft servers are down.

**Comment by TLeonardUK** [comment]
Does Convergence modify the game's exe at all? It might be offseting the key that needs to be patched. 

Otherwise I'm not sure, if you can send the server log for around the time you attempt to connect that might help.

**Comment by NaliAroni** [comment]
I don't even get to the dev logos unfortunately, so I don't think the server log will help. Game launches normally without using the server loader though. I don't beleive the mod edits the .exe based on the uninstallation instructions.

https://i.imgur.com/wXsJtkm.png: taken from https://www.nexusmods.com/darksouls3/mods/672

I do have a vanilla copy of the game as well, and that loads and connects just fine.

**Comment by TLeonardUK** [comment]
Do you use blue sentinel by any chance? If you do, can you try booting the game via ds3os with and without it, just want to double check its not causing issues, as I've seen some bugs in their nexusmods bugs for similar behaviour.

**Comment by NaliAroni** [comment]
I did uninstall blue sentinel while trying to troubleshoot this myself. I even went so far as to reinstall the game and moding it from fresh.

**Comment by TLeonardUK** [comment]
Thanks for the info.

**Comment by ExTremZero** [comment]
my friend had the same issue, but when he tries to start the game via steam, it works fine, but when he started it trought the newest loader it crashes, with loader version 12 it works again

**Comment by IndieanaJones** [comment]
I can confirm with the current version of the launcher (version 12) Convergence works fine.

**Comment by Ryu776** [comment]
what was the solution to this? a friend of mine is having this exact issue. me and another friend have been playing fine for a few days and when we try to get our 3rd friend in now he starts having this issue. fire wall is disabled, antivirus doesn't pick it up, he's tried fresh installations for both the game and the mod and it still wont startup. it launches fine through steam but not through the server loader. i'm at a complete loss and i cant even get a solution from their discord.
