### ISSUE TITLE
[CRASH] Server.exe can't start on Windows Server 2019 Datacenter x64

### ISSUE THREAD

**Issue by KouYiGuo** [TLeonardUK/ds3os#47]
Firstly, Thanks for the amazing project !

I have a cloud server, which run **Windows Server 2019 Datacenter (x64)**, and has 4G RAM.

When I run the **Server.exe** on it, **Server.exe** crash immediately.

**Server.exe** version is **v0.9.0.0-main**.

Here is the log:
```
Faulting application name: Server.exe, version: 1.0.0.0, time stamp: 0x61f1c074
Faulting module name: ucrtbase.dll, version: 10.0.17763.1490, time stamp: 0x48ac8393
Exception code: 0xc0000409
Fault offset: 0x000000000006e77e
Faulting process id: 0x9e4
Faulting application start time: 0x01d813335dc53968
Faulting application path: C:\Users\Administrator\Desktop\Binaries\Server\Server.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
```

**Comment by TLeonardUK** [comment]
Try and get a minidump if you can, thats more useful for diagnosing crashes, and any logs from the server. If the server doesn't even get to the point of emitting any output my guess is your missing the relevant VC redistributables, you can get them here - https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by KouYiGuo** [comment]
I use **windbg** to run **Server.exe**, and get some log like this.

<img width="1027" alt="截屏2022-01-28 10 24 02" src="https://user-images.githubusercontent.com/66426025/151476478-86c0d320-8281-4ad6-a394-62dace4766f2.png">

Does it help?

**Comment by KouYiGuo** [comment]
I'm sure that I have installed the **VC_redist.x64** on server.

**Comment by KouYiGuo** [comment]
<img width="1011" alt="截屏2022-01-28 11 36 44" src="https://user-images.githubusercontent.com/66426025/151543964-5b5fd586-249a-45f7-8bdb-e4884906bb4b.png">

Here is the **key** log.

The problem is that I need install steam client when I run the **Server.exe**. I have add a note in the README.md.

**Comment by TLeonardUK** [comment]
I should actually be able to get that running without stream being installed. Think I just need to redistribute the right dlls.
