### ISSUE TITLE
Not Advertised Error

### ISSUE THREAD

**Issue by corVulpe** [TLeonardUK/ds3os#49]
Hi
I did everything on your readme. I port forwoarded, set the server name and private server name as my ip at whatismyip.com. Also tried out my ipv4 but i cant connect to server. Whenever i try to connect to server on the loader it fails and after than it says -Not Advertised- under the player count. I tried the older releases but still cant fix it.

Thanks for interesting.

**Comment by TLeonardUK** [comment]
Your private hostname should be your LAN address not your WAN address, that will be why its failing.

Not advertised is normal if your importing the server from a file rather than just viewing it on the master server list.

**Comment by TLeonardUK** [comment]
https://github.com/TLeonardUK/ds3os/discussions/categories/help-support

Can you put help requests in there please, trying to keep the issues list for bug reports.
