### ISSUE TITLE
Server.exe overwrites the server.ds3osconfig settings and config.json has no effect

### ISSUE THREAD

**Issue by Adephx** [TLeonardUK/ds3os#5]
I have several ethernet adapters (running Hyper-V) and the Ethernet adapter vEthernet (Default Switch) has to be the highest priority due to latency issues. I am unable to change the Server.exe public and private IP, which is especially problematics as I use two different IP pool in my network.

Can you add an option which enables manual IP settings?

**Comment by TLeonardUK** [comment]
Overwriting the file is by-design, that file is just meant to be a template, its updated with whatever settings are set in config.json / the crypto keys each run. It's expected you copy it elsewhere, make whatever modifications you want to it, then send it to whoever needs it.

At the moment the sockets the server creates are set to listen on all interfaces, so as long as you make a copy of that file and set it up appropriately the connections should be made to the correct IP address. If its not, thats a bug.
