### ISSUE TITLE
[BUG] Any online interactions suddenly unusable

### ISSUE THREAD

**Issue by Jeebanana** [TLeonardUK/ds3os#56]
I've been doing invasions in servername's server and after some time i suddenly couldn't invade anyone. My red eyes or signs would get cancelled, i would get invasions cancelled messages a lot and nobody could see my signs even if i manage to put them down. 

I check Pyre Protecc's logs and see this message:

[libprotobuf ERROR ..\src\google\protobuf\message_lite.cc:123] Can't parse message of type "Frpg2RequestMessage.RequestGetSignListResponse" because it is missing required fields: (cannot determine missing fields for lite message)

Good luck. If you need more info my discord is: Pythoneer Reaper#8344

**Comment by TLeonardUK** [comment]
v0.12 fixes the protobuf error, give that a try and see if it helps. That said I'm not 100% sure if its related.

v0.12 is building at the moment, just monitor https://github.com/TLeonardUK/ds3os/releases, should be up in 15 minutes.
