### ISSUE TITLE
getting failed to decrypt rsa message error

### ISSUE THREAD

**Issue by Grabisoft** [TLeonardUK/ds3os#6]
![adsad](https://user-images.githubusercontent.com/16512014/133346567-c01b2fa8-0f82-421c-8251-d64bb3f21ed6.png)

hi sorry for my message , any suggestions? PC hoster can join fine, but the other PC cant

**Comment by TLeonardUK** [comment]
The other PC is trying to connect using the public key for the server.

How are they connecting? Via a ds3sconfig file or via an advertised server?
