### ISSUE TITLE
Crashes when using Blue Sentinel

### ISSUE THREAD

**Issue by Jrgykins** [TLeonardUK/ds3os#92]
Doing a new playthrough with some friends on a public custom server but the game keeps crashing consistently at the begining of certain boss fights when friendly phantoms are present (have not done testing with hostile phantoms). So far the only bosses affected are Curse-Rotted Greatwood and High Lord Wolnir. I've attached the logs Blue Sentinel generated.
[BlueSentinelLog_22-02-01.txt](https://github.com/TLeonardUK/ds3os/files/8009351/BlueSentinelLog_22-02-01.txt)
[BlueSentinelLog_22-02-03.txt](https://github.com/TLeonardUK/ds3os/files/8009352/BlueSentinelLog_22-02-03.txt)
[BlueSentinelLog_22-02-05.txt](https://github.com/TLeonardUK/ds3os/files/8009353/BlueSentinelLog_22-02-05.txt)

**Comment by TLeonardUK** [comment]
You should report this to Blue Sentinels developers as this doesn't occur without it.
